### ISSUE TITLE
No suitable driver found for jdbc:postgresql on DT 6.1

### ISSUE THREAD

**Issue by tbikeev** [dynaTrace/Dynatrace-Log-File-Monitor#1]
( duplicate of https://community.compuwareapm.com/community/display/DL/Log+File+Monitor?focusedCommentId=186533942#comment-186533942 )

Hi, I have tried a fresh install of Log File Scraper 3.5.17 on DT 6.1 ( that otherwise writes Performance Warehouse data into postgres with no issues ).

For the plugin though I am getting:

2015-04-16 11:02:20 INFO [com.logfile.WP@APE Monitor_0] Log ID 0: No New Message
2015-04-16 11:02:20 WARNING [com.logfile.WP@APE Monitor_0] java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:/dt_plugins?user=ZZZ&password=XXX

meaning that the plugin can not reach the DB that has been setup for it.

Am I missing something driver-wise for DT6+ ?

Regards, Thomas

**Comment by JoshuaRaymond** [comment]
Hey Thomas,

I just created [release 3.15.8](https://github.com/dynaTrace/Dynatrace-Log-File-Monitor/releases/tag/v3.15.8) to contain an updated driver for PostgreSQL.  Can you please implement this updated version and let me know if it resolves your issue?

Thanks,
Josh Raymond

**Comment by tbikeev** [comment]
Supplying default :5432 PG port resolves the problem.
